[".local/share/wallpapers"]
	type = "git-repo"
	url = "https://github.com/dracula/wallpaper.git"
	refreshPeriod = "168h"
[".themes"]
	type = "archive"
	url = "https://github.com/dracula/gtk/archive/master.zip"
	refreshPeriod = "672h"
[".icons"]
	type = "archive"
	url = "https://github.com/dracula/gtk/files/5214870/Dracula.zip"
	refreshPeriod = "672h"
