# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: \.tmpl$
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
        exclude: \.tmpl$
      - id: check-yaml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
