# ~/tokei.toml
# =============================================================================
# Tokei config file, for counting lines of code
#
# See:
# - https://github.com/XAMPPRocky/tokei

# Count hidden files and directories.
hidden = true
# Sort languages based on column [possible values: files, lines, blanks, code, comments]
sort = "code"
