#!/bin/sh

# post-checkout hook - looks for changes to package-lock.json,
# when you change branches, and if found, reinstalls the given packages every

# Adapted from: https://gist.github.com/8bitDesigner/5869846

# Exit early if this was only a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

oldRef=$1
newRef=$2

function changed {
  git diff --name-only $oldRef $newRef | grep "^$1" > /dev/null 2>&1
}

# js package managers
## bun install
if changed 'bun.lockb'; then
  echo "📦 bun.lockb changed. Running bun install to bring your dependencies up to date."
  bun install
fi

## npm install
if changed 'package-lock.json'; then
  echo "📦 package-lock.json changed. Running npm install to bring your dependencies up to date."
  npm install
fi

## pnpm install
if changed 'pnpm-lock.yaml'; then
  echo "📦 pnpm-lock.yaml changed. Running pnpm install to bring your dependencies up to date."
  pnpm install
fi

## yarn install
if changed 'yarn.lock'; then
  echo "📦 yarn.lock changed. Running yarn install to bring your dependencies up to date."
  yarn install
fi
